export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";

export const START_EDITING_SERVICE = "START_EDITING_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
